### ISSUE TITLE
Cannot connect to user from multiOTP credential provider

### ISSUE THREAD

**Issue by Storck1** [multiOTP/multiotp#41]
hello,
i'm explaining my situation, i'm in my working to intergrat a sever/client Windows with OTP in loging for a project in my study. I'm using WIndows 2016 and Windows 10/7.

I have set the server like it's recommended in the section "HOW TO CONFIGURE MULTIOTP TO SYNCHRONIZED THE USERS FROM AN ACTIVE DIRECTORY ?" and in local of my serv i can access to the user i have created. But when i want to use MultiOTP credential Provider, i have all the time an error like the user doesn't exist. And if i do the same configuration for the AD sync (dunno if we must do it on the client), i have errror message than authentication have failed 

![capture](https://user-images.githubusercontent.com/43173108/45375137-67079d00-b5f4-11e8-882c-60dccd9e9347.PNG)

![capture2](https://user-images.githubusercontent.com/43173108/45375310-e5643f00-b5f4-11e8-9c20-e036448acdc2.PNG)

![capture3](https://user-images.githubusercontent.com/43173108/45375311-e5643f00-b5f4-11e8-908b-df21a20e1331.PNG)
have you any idea what i did wrong ? 

Config.ini in W7:

multiotp-database-format-v3
; If backend is set to something different than files,
; and backend_type_validated is set to 1,
; only the specific information needed for the backend
; is used from this config file.

encryption_hash=99CCFC0D033729754B6BB4832FE786A1
server_secret:=RGV3ZXVq
actual_version=5.3.0.3
admin_password_hash:=
anonymous_stat=1
anonymous_stat_last_update=1536684749
anonymous_stat_random_id=3a8240efd7bcdaf79c908ea522d0615e8429a3e5
attributes_to_encrypt=
auto_resync=1
backend_encoding=UTF-8
backend_type=files
backend_type_validated=0
cache_data=0
cache_ldap_hash=1
case_sensitive_users=0
clear_otp_attribute=
console_authentication=0
create_host=W10PC
create_time=1536684549
debug=0
default_algorithm=totp
default_dialin_ip_mask=
default_user_group=
default_request_ldap_pwd=1
default_request_prefix_pin=1
demo_mode=0
developer_mode=0
display_log=0
domain_name=
email_admin_address=
encode_file_id=0
encryption_key_full_path=
failure_delayed_time=300
group_attribute=Filter-Id
hash_salt_full_path=
issuer=multiOTP
language=en
last_sync_update=0
last_sync_update_host=
last_update=1536685182
last_update_host=W10PC
ldap_expired_password_valid=1
ldap_account_suffix=
ldap_activated=0
ldap_base_dn=
ldap_bind_dn=
ldap_cache_folder=tempdir
ldap_cache_on=1
ldap_cn_identifier=sAMAccountName
ldap_default_algorithm=totp
ldap_domain_controllers=
last_failed_white_delay=60
ldap_group_attribute=memberOf
ldap_group_cn_identifier=cn
ldap_users_dn=
ldap_hash_cache_time=604800
ldap_in_group=
ldap_language_attribute=preferredLanguage
ldap_network_timeout=10
ldap_port=389
ldap_recursive_cache_only=0
ldap_recursive_groups=1
ldap_server_password:=
ldap_server_type=1
ldap_ssl=0
ldap_synced_user_attribute=
ldap_time_limit=30
ldaptls_reqcert=auto
ldaptls_cipher_suite=auto
log=0
max_block_failures=6
max_delayed_failures=3
max_event_resync_window=10000
max_event_window=100
max_time_resync_window=90000
max_time_window=600
multiple_groups=0
ntp_server=pool.ntp.org
overwrite_request_ldap_pwd=1
radius_error_reply_message=1
radius_reply_attributor= += 
radius_reply_separator_hex=2c
radius_tag_prefix=
scratch_passwords_digits=6
scratch_passwords_amount=10
self_registration=1
server_cache_level=1
server_cache_lifetime=15552000
server_timeout=5
server_type=xml
server_url=https://192.168.1.5:8112
sms_api_id:=
sms_message_prefix=%s is your SMS-Code
sms_originator=multiOTP
sms_password:=
sms_provider=
sms_userkey:=
sms_digits=6
sms_timeout=180
smtp_auth=0
smtp_password:=
smtp_port=25
smtp_sender=
smtp_sender_name=
smtp_server=
smtp_ssl=0
smtp_username=
sql_server=
sql_username=
sql_password:=
sql_database=
sql_schema=
sql_config_table=multiotp_config
sql_cache_table=multiotp_cache
sql_devices_table=multiotp_devices
sql_groups_table=multiotp_groups
sql_log_table=multiotp_log
sql_tokens_table=multiotp_tokens
sql_users_table=multiotp_users
syslog_facility=7
syslog_level=5
syslog_port=514
syslog_server=
tel_default_country_code=
timezone=Europe/Zurich
token_serial_number_length=12
token_otp_list_of_length=6
verbose_log_prefix=

Config.ini in W16:
multiotp-database-format-v3
; If backend is set to something different than files,
; and backend_type_validated is set to 1,
; only the specific information needed for the backend
; is used from this config file.

encryption_hash=99CCFC0D033729754B6BB4832FE786A1
server_secret:=RGV3ZXVq
actual_version=5.3.0.3
admin_password_hash:=RGAzPSxXYhR9KVE5dScSKCcpNTxNbCIZCHM3NSpnGn0=
anonymous_stat=1
anonymous_stat_last_update=1536684195
anonymous_stat_random_id=2219aad31f3d11d9a582b1a4a33e60dc0d840de9
attributes_to_encrypt=
auto_resync=1
backend_encoding=UTF-8
backend_type=files
backend_type_validated=0
cache_data=0
cache_ldap_hash=1
case_sensitive_users=0
clear_otp_attribute=
console_authentication=0
create_host=WIN-J84TRP59L2L
create_time=1536684195
debug=0
default_algorithm=totp
default_dialin_ip_mask=
default_user_group=
default_request_ldap_pwd=1
default_request_prefix_pin=0
demo_mode=0
developer_mode=0
display_log=0
domain_name=
email_admin_address=
encode_file_id=0
encryption_key_full_path=
failure_delayed_time=300
group_attribute=Filter-Id
hash_salt_full_path=
issuer=multiOTP
language=en
last_sync_update=0
last_sync_update_host=
last_update=1536684467
last_update_host=WIN-J84TRP59L2L
ldap_expired_password_valid=1
ldap_account_suffix=
ldap_activated=1
ldap_base_dn=DC=projetotp,DC=local
ldap_bind_dn=CN=administrateur,CN=Users,DC=projetotp,DC=local
ldap_cache_folder=tempdir
ldap_cache_on=1
ldap_cn_identifier=sAMAccountName
ldap_default_algorithm=totp
ldap_domain_controllers=projetotp.local,ldaps://192.168.1.5:389
last_failed_white_delay=60
ldap_group_attribute=memberOf
ldap_group_cn_identifier=sAMAccountName
ldap_users_dn=
ldap_hash_cache_time=604800
ldap_in_group=UtilisateursOTP
ldap_language_attribute=preferredLanguage
ldap_network_timeout=20
ldap_port=389
ldap_recursive_cache_only=0
ldap_recursive_groups=1
ldap_server_password:=BkRzfEYy
ldap_server_type=1
ldap_ssl=0
ldap_synced_user_attribute=
ldap_time_limit=30
ldaptls_reqcert=auto
ldaptls_cipher_suite=auto
log=0
max_block_failures=6
max_delayed_failures=3
max_event_resync_window=10000
max_event_window=100
max_time_resync_window=90000
max_time_window=600
multiple_groups=0
ntp_server=pool.ntp.org
overwrite_request_ldap_pwd=1
radius_error_reply_message=1
radius_reply_attributor= += 
radius_reply_separator_hex=2c
radius_tag_prefix=
scratch_passwords_digits=6
scratch_passwords_amount=10
self_registration=1
server_cache_level=1
server_cache_lifetime=15552000
server_timeout=5
server_type=xml
server_url=
sms_api_id:=
sms_message_prefix=%s is your SMS-Code
sms_originator=multiOTP
sms_password:=
sms_provider=
sms_userkey:=
sms_digits=6
sms_timeout=180
smtp_auth=0
smtp_password:=
smtp_port=25
smtp_sender=
smtp_sender_name=
smtp_server=
smtp_ssl=0
smtp_username=
sql_server=
sql_username=
sql_password:=
sql_database=
sql_schema=
sql_config_table=multiotp_config
sql_cache_table=multiotp_cache
sql_devices_table=multiotp_devices
sql_groups_table=multiotp_groups
sql_log_table=multiotp_log
sql_tokens_table=multiotp_tokens
sql_users_table=multiotp_users
syslog_facility=7
syslog_level=5
syslog_port=514
syslog_server=
tel_default_country_code=
timezone=Europe/Zurich
token_serial_number_length=12
token_otp_list_of_length=6
verbose_log_prefix=

thx for the replay 

Regards

Arnaud

Edit: added the config.ini for more information
Edit: Add server log error info:

> multiotp 5.3.0.3
> Your script is running from C:\multiotp\windows\
> 2018-09-12 11:45:40	debug		Server-Client	Info: *CheckUserExists server request for 1 with challenge }FY_jfE3#3d5affe2ki jc1&0541eb38
> 2018-09-12 11:45:40	debug		Server-Client	Info: *CheckUserExists intermediate error code: 70
> multiotp 5.3.0.3
> Your script is running from C:\multiotp\windows\
> 2018-09-12 11:45:40	debug		Server-Client	Info: *ReadUserData server request for user1

Update :  12.09.2018 :15:24

i succeded the settings of the client, but i used a "trick". I had to take the users on the server (user file in MultiOTP) and copy them on the client, because the users who were created on the client wasn't working.

any clue where is the problem ?

**Comment by kaushikb1996** [comment]
@Storck1 Can you throw some more light on how you managed to get it working, since I am facing the same issue.

**Comment by multiOTP** [comment]
Hello Storck1,
we have published a new 5.4.0.1 version of multiOTP which should correct the issue.
Could you give it a try and let us know if it's ok now ?
Best regards

**Comment by kaushikb1996** [comment]
@Storck1 

Version: 5.4.0.1
Windows: Tested on 7/8.1/10



I have tested the new version and I am still facing the same issue. Firstly I am trying to install on my local machine. There is a user file which is begin generated and stored in the mutliotp/users folder but in the credential provider it's displaying that the user doesn't exist. So I went ahead and ran checkmultiotp and identified couple of things. One is that nircmd is missing from the tools folded so it was passing 24/28 tests. Post adding nircmd All the tests have passed (27/28) expect for the one linked to radius server I suppose, which is returning this error -> `radclient: received bad packet: Error receiving packet: An existing connection was forcibly closed by

ALSO I HAVE ENTERED THE VALID TOTP (Not represented in the image)
![s1](https://user-images.githubusercontent.com/5248406/45568962-0609e000-b813-11e8-9ab9-38728b6a76c1.PNG)
![s2](https://user-images.githubusercontent.com/5248406/45568963-0609e000-b813-11e8-8051-9a24b1b8955e.PNG)

 the remote host.`

Few more things I would like to add

- I can see the users from the web service and also I have verified that the TOTP's are working by the webservice.
- The Credential Provider from LastSquirrelIT Release 3.0 RC1 seems to work, but it has its own set of bugs.
- The new credential Provider is returning -> User doesn't exist and Status not activated 


Please let me know if you need any additional configuration/environment issues you require from my end.

Cheers, 
Kaushik Bharadwaj

**Comment by multiOTP** [comment]
Hello Kaushik,
Please be sure that multiOTP server is also in version 5.4.0.1, because the fixed issue is when cache information is given back from the server to the client.
Regards,

**Comment by kaushikb1996** [comment]
@multiOTP Hey, thanks for the quick response. But I am trying to do a LOCAL ONLY STRONG setup. It would be great if you can guide me through to resolve the issue if it's on my end.

**Comment by multiOTP** [comment]
Hello Kaushik,
Sorry for misunderstanding clearly your issue.
Where did you install the multiOTP Credential Provider (which path) during the installation process ?
How did you exactly create the multiotp user kaushik ?
Regards,

**Comment by multiOTP** [comment]
Did you do like written in the README file ?

LOCAL ONLY STRONG AUTHENTICATION INSTALLATION
=============================================
1) Install the multiOTP Credential Provider, which contains also multiOTP inside.
2) During the installation, specify the folder on the client where the
   multiotp.exe file and folders must be installed and configured.
3) In the wizard, leave the URL of the multiOTP server(s) empty.
4) You can also choose to require a strong authentication only for RDP.
5) When you are on the test page, open a command prompt in the folder where
   multiOTP is now installed and create a new local user. Example:
   1) *multiotp -fastcreatenopin my_user*
   2) *multiotp -qrcode my_user my_qrcode.png)*
6) If the test is successful, the Credential Provider is installed.
7) To disable the Credential Provider, uninstall it from Windows,
   or execute multiOTPCredentialProvider-unregister.reg

**Comment by kaushikb1996** [comment]
@Storck1 
For some more context this is the use case I am looking at: To run multiotp on a single local/RDP machine where in this would replace the windows login with multiotp for multi factor authentication 

OK, I have now changed the installation path of  Credential Provider to where the mutliotp folder is present ( C:\multiotp ) and now went ahead ran these commands 
`multiotp -fastcreatenopin kaushik`
`multiotp -qrcode kaushik my_qrcode.png`

and scanned the QR Code from the admin Panel ( http://127.0.0.1:8112/?method=PrintQrCode&options=kaushik )

Now I have got a validated message in the credential provider.

![s1](https://user-images.githubusercontent.com/5248406/45581245-674fa480-b84f-11e8-925f-888fd14e0884.PNG)


So I sign out to check if it's activated. But then I am again shown the default Windows login. Even tried rebooting but still shows the windows login and I ran the Credential Provider again and it still says validated and active.

**Comment by kaushikb1996** [comment]
@multiOTP Went ahead and did a fresh install of cred provider, with the configuration you have mentioned.
![s2](https://user-images.githubusercontent.com/5248406/45581558-29557f00-b855-11e8-8e4e-741324f8b0eb.PNG) 
got it running with installed and activated

and issue still persists, Sign out/Reboot still take me to default Windows login.

PS:

- Running Windows 10
- The Credential Provider from LastSquirrelIT Release 3.0 RC1 seems to work, but it has it's own set of bugs.
- Let me know if you need any additional info my end!

**Comment by Storck1** [comment]
Hello @multiOTP ,

I just Installed the new version on my test server at home and it seams to work well ! 

thanks alot for your help and your  modification

**Comment by pbssubhash** [comment]
@Storck1, are you sure you're not getting the issue mentioned by Kaushik with respect to the 2FA login not being visible? 

Also, if it's working perfectly fine, can you please mention the steps you've taken? It'd be a checklist for us.

**Comment by kaushikb1996** [comment]
Hey @multiOTP ,

I am able to get it working by using an old Credential Provider ( mOTP-CP-2.1.2-RC2-x64-eng.zip ). So I suppose that the issue is with the new Credential Provider. If you could emulate a 64x Windows 10 system to test the new Credential Provider for a local authentication setup it would be great! As in we can check whether it's a global issue or If I have made any mistakes while setting up. 

Cheers!

**Comment by Storck1** [comment]
> @Storck1, are you sure you're not getting the issue mentioned by Kaushik with respect to the 2FA login not being visible?
> 
> Also, if it's working perfectly fine, can you please mention the steps you've taken? It'd be a checklist for us.

i had this problem but after litle research it was an update who was missing (when i tried on W7 i had a missing DLL dll-msvcp140.dll) and after cheaking on internet it was a Microsoft Visual C++ runtime who was missing.

After few test, i can say that it work but not with 100%.
i explain myself, i can make it work but for that i must connect first with the CMD on the client, if i don't do that i have the message user doesn't exist (in Credential Provider) and after that if i try to connect with a user i didn't try with CMD i cannot connect. 
(if in the CMD i have connect with User1 but not User2. on the login Windows i cannot connect to User2, i must connect him with the command in the CMD)

I think when we install the programm it doesn't really syncronize the user so actually you have to do it by hand (with the CMD commande : multiotp -display-log -log -debug "user" "otp"

i don't know if it's clear what i said, don't be afraid to ask more details (btw my mother tongue is french sorry for the bad english)

but anyway i can continue my project and i'm realy thankful of your work  !

**Comment by multiOTP** [comment]
Hello,
exactly it doesn't synchronise the users. It only keep a cache locally on the computer once the user has loged-in on the pc with access to the multiOTP server then the credentials are cached.
Hope this helps.
Have a  great day.

**Comment by multiOTP** [comment]
Please note that VC++ redistributable libraries are now included in the installer.

**Comment by pogosyan-it** [comment]
Dear developers.
I have the same problem with your product - when I'm trying to authentificate on my windows server 2019 I revice an error: "TOTP password is wrong".  The version of the multiotp is 
root@f9d7ff3a4d91:/# cat /etc/multiotp/config/multiotp.ini | grep version
actual_version=5.9.5.5
The verion of credentialProvider is 5.9.6.1
I'm using AD authentification.  On my TOTP web interface I can see all users in group which was set in container. 
"DeletePrintScratchlistResync yrpogosyan [AD/LDAP]"
Both tests, one from web interface (check a user), another from container succeed:
_root@f9d7ff3a4d91:/# multiotp -display-log yrpogosyan 569647
LOG 2024-04-14 19:47:50 notice (user yrpogosyan) User OK: User yrpogosyan successfully logged in with TOTP token_
But in cmd-line from windows server (where this cred provider is installed)  I'm receiving exectly the same answer as was posted by  Mr. Storck1 on Sep 11, 2018 on the top of this issue. When I'm checking the directory _**users**_ in Program files\multiotp it appears to be empty.  The firewall on the windows server is turned off, the server is in domain. 
The Linux server where container is deployed and windows server are in the same network. 
Can you help me with this ptoblem? Thank you in advance.
